---
title: "analysis_text.Rmd"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

討論議題
1. 犯罪心理相關分析：
　　《黑貓》篇幅不長，但是作者對於情節的配置、結構的安排、以及心理的描述都非常仔細。作為一個男主角虐貓殺人的故事，其中並沒有使用到血腥的刻畫，然而文本之中有許多暴力和負面的形容。
　　我們想要試著從「犯罪心理」的角度切入探討，透過詞頻分析，找出罪犯的語言特徵，進而製作一個情緒光譜（以光明、善良等詞彙為例，靠近「正值」，而憤怒、冷酷等詞彙則列在「負值」）。最後依據這個情緒光譜與分類，從臉書、PTT等平台上的發文判斷哪些使用者傾向負值較多，這些使用者或許會需要心理上的諮商及協助。
2. 精神狀況相關分析：
　　《黑貓》的故事情節隨著作者心境轉折，閱讀時可以察覺文字編排從原先的言之有物，至後期不知所云的變化。這樣的狀況在真實生活之中也能夠看到（例如芭蕾舞者「尼金斯基筆記」）。
　　與犯罪心理討論的方向相近，也是利用詞頻等分析與其他平台上的使用者發文作比對，期望找到有潛在精神崩潰的狀況的人，以及早預防。
　　為了提升資料的信度，我們覺得也許可以運用R的技術製作一個語料庫，其中包含非常多作者的作品，並加以訓練一個模型。首先對《黑貓》進行檢驗，如果作品前後風格差異真的很大，模型也會把作品前後分成兩個不同的群集。
3. 作品分析：《黑貓》為一哥德式小說，其中包含許多恐怖元素。
　　可以運用R來與其他恐怖小說做對比，找尋恐怖小說常使用的元素。
可能遇到的問題
1. 技術問題：
　　雖然想製作多位作者的語料庫、訓練模型，不過目前的課程還沒有學習到機器學習相關的事情。
2. 理論問題：
　　我們在網路上有看到探討利用社群網站追蹤使用者用詞，並加以觀察使用特定負面或正面字彙時腦部的活絡狀況的文章，可是也有其他文章提出文字上的訊息對於預測自殺行為的效果有限（以Linkin Park主唱的事件為例，甚至可以說根本沒辦法透過社群網站上的發文觀察出來）。還是需要加入使用者的健康資料一起討論觀察，才能夠更加準確地追蹤。
3. 倫理問題：
　　想要取得社群網站上的發文並加以分析、或是取得使用者的健康資料，都可能涉及使用者的隱私問題。